language: ruby
rvm:
  - "2.4.1"
before_script:
  - psql -c 'create database cont_test' -U postgres
  - RAILS_ENV=test bundle exec rake --trace db:migrate
script:
  - bundle exec rake ci:tests
notifications:
    slack: cto2:WwdBwC6t19iymGA55fEEt0PX
